# --- General options --- #

# Full website URL
url: "https://aufhebung.fr"

# Website's URL without the hostname
baseurl: ""

# jekyll-seo-tags inserts the <title> using 'title' var as "<title>{{ page.title }} | {{ seo.title }}</title>"
title: "AUFHEBUNG"
author: "Collectif Aufhebung"
description: "Pour une critique radicale du faux omniprésent"

logo: /img/aufhebung_logo_large.png
lang: fr_FR

# --- Social medias ---#

facebook:
    publisher: https://www.facebook.com/AufhebungOfficiel/
    
social:
    links:
        - https://youtube.com/c/Aufhebung
        - https://facebook.com/AufhebungOfficiel/

# Relative path used by _includes/head.html
og_image_rpath: /img/aufhebung_logo_large.png

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
    BLOG: /
    ARTICLES: /articles
    BIBLIOTHÈQUE: /bibliotheque

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: favicon.ico

# --- Footer --- #
footer: "Aucun droit réservé sur rien."

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "aufhebung.fr"

# --- Others ---#

# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: "Collectif Aufhebung"

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 35

# Output options (more information on Jekyll's site)
timezone: "Europe/Paris"
highlighter: rouge
permalink: /:year-:month-:title/

markdown: kramdown
kramdown:
  toc_levels: 1..4

# Publish posts of a future date
future: false

paginate: 10
paginate_path: "/page:num/"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - .git
  - .gitignore
  - LICENSE
  - README.md
  - build_aux/
  - Makefile
  - "*.xcf"

plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tags
  - jekyll-sitemap


collections:
  articles:
    output: true
  bibliotheque:
    output: true
